### PR TITLE
Et upgrade apr 1st

### PR DESCRIPTION
**Pull request by kanxuUCHI**
1) Update default setting of functions: set default value of w to 0.5, and that of standard deviation to 1;
2) Create tests to make sure functions return the same value as the original functions (homogeneous case) if sd = 1 and w = 0.5;

### CODE REVIEW

**Comment by pcarbo** [comment]
Hi @kanxuUCHI, I'm getting an error from this example in `ebayesthresh.Rd`:

```R
ebayesthresh(x = rnorm(100, c(rep(0,90),rep(5,10))),
             prior="cauchy", sdev = NA)
# R> Error in postmed(x, s, w, prior = prior, a = a) :
# R> Standard deviation is not allowed for Cauchy prior.
```

I don't understand what is means that "standard deviation is not allowed". Does it mean that the variance must be homogeneous? Perhaps you need to fix `postmed` and `postmean` so that it only reports an error when the variances/s.d.'s are different?

**Comment by kanxuUCHI** [comment]
@pcarbo I thought you were talking about returning error when some value is passed to standard deviation.
```
+ Please return an error (`stop("...")`) whenever `s` or `sdev` is supplied but should be ignored or is not applicable (e.g., with `postmean(prior = "cauchy")`). Use `missing` function to check this.
```

**Comment by pcarbo** [comment]
@kanxuUCHI I see your point. However, it seems like a bug if you are calling `postmed(s = x,prior = "cauchy")` when argument `s` is not relevant for the Cauchy prior. Why are you setting the standard deviation when the Cauchy prior is being used?

It seems that there are too options for resolving this issue:

1. Allow for setting `s` when Cauchy prior is used, but ignore this argument, and don't generate errors or warnings (perhaps easier to implement, but less preferrable because could lead to user mistakes).

2. Report an error whenever `s` is passed as argument when `prior = Cauchy` (more preferrable, but perhaps more difficult to implement).

What do you think is the better option?

**Comment by kanxuUCHI** [comment]
@pcarbo The error you get is from `ebayesthresh`, where I initially passed standard deviation whatever the prior was. To avoid the error in `ebayesthresh` and still return an error using `postmean/postmed`, I think I have to add extra conditions in `ebayesthresh`. One trick would be to report an error in `postmean/postmed` only when `s!=1` since the standard deviation defaults to 1 for `postmean/postmed`.

**Comment by pcarbo** [comment]
@kanxuUCHI I'm not familiar with the model with the Cauchy prior. Is the standard deviation argument ignored for the Cauchy prior because it is irrelevant (i.e, there is no s.d. parameter for this model), or because only one possible setting of the standard deviation is allowed (e.g., `s = 1`)? We should design the error handling based on what fits with the model.

**Comment by kanxuUCHI** [comment]
@pcarbo Yes, only one setting (s=1) is allowed. In the original package, these functions are seldom used directly and all these functions serve `ebayesthresh`. Most of the functions take standard deviation to be 1 (and no other options) because in `ebayesthresh` the standard deviation will be stabilized to 1. I don't want to change the default setting too much and only allow standard deviation to be vary for laplace prior. The standard deviation will be passed directly to these functions without any stabilization for both homogeneous and heterogeneous cases.

**Comment by pcarbo** [comment]
@kanxuUCHI It sounds like what you suggested above for `postmed` and `postmean` (and perhaps other functions) would be a good option. Although I would modify it slightly and report an error, and allow for a vector:

```R
if (!missing(s)) {
  if (any(s != 1))
    error("Only s.d. of 1 is allowed for Cauchy prior.")
}
```

Note if you set the default to `s = 1` then the code is even simpler:

```R
if (any(s != 1)) 
    error("Only s.d. of 1 is allowed for Cauchy prior.")
```

**Comment by kanxuUCHI** [comment]
I agree. It would be good enough to report error when any value in the standard deviation vector passed to `postmean/postmed` is not equal to one. I have updated `postmean/postmed`.

**Comment by pcarbo** [comment]
@kanxuUCHI Thank you for making these revisions.

A couple additional questions:

+ I see you added a file, `EB_Update_CompVal.R`. Is this meant to be part of the package? Or were you just using it for testing your code? Do you want to keep it in the repository?

+ In `test_ebayesthresh.R` you added a note, "the failure of this test is due to a refinement of the search domain of threshold." However, the test passed for me. Are you expecting the test to fail?

**Comment by kanxuUCHI** [comment]
@pcarbo `EB_Update_CompVal.R` is only used to create the expected value so it's not necessarily to be there. I used the return of my current updated package to be the expected value and the original functions in `test_ebayesthresh.R`. So it will give different results here.

**Comment by pcarbo** [comment]
@kanxuUCHI This is the result I got from running the CRAN version of `EbayesThresh`:

```R
set.seed(123)
x <- rnorm(100)
print(tfromx(x),digits=12)
# 3.03485425655
```

So it is nearly the same answer as your implementation. What do you mean by the results being different?

**Comment by pcarbo** [comment]
@kanxuUCHI I think I understand now… the comment you added refers to the test for `tfromw`?

**Comment by kanxuUCHI** [comment]
@pcarbo Exactly, sorry for the confusion.

**Pull request merged**
